### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ims2098** [Talend/tmdm-server-se#1639]
I'm getting this error trying to build org.talend.mdm.core.storage.sql
[ERROR] Failed to execute goal on project org.talend.mdm.core.storage.sql: Could not resolve dependencies for project org.talend.mdm:org.talend.mdm.core.storage.sql:jar:8.8.8-SNAPSHOT: Failed to collect dependencies at org.talend.mdm:org.talend.mdm.core:jar:8.8.8-SNAPSHOT -> org.talend.mdm:org.talend.mdm.commons.core:jar:8.8.8-SNAPSHOT -> net.sourceforge.saxon:saxon9-dom:jar:9.0.0.8: Failed to read artifact descriptor for net.sourceforge.saxon:saxon9-dom:jar:9.0.0.8: Could not transfer artifact net.sourceforge.saxon:saxon9-dom:pom:9.0.0.8 from/to thirdparty-releases (https://artifacts-zl.talend.com/nexus/content/repositories/thirdparty-releases): authentication failed for https://artifacts-zl.talend.com/nexus/content/repositories/thirdparty-releases/net/sourceforge/saxon/saxon9-dom/9.0.0.8/saxon9-dom-9.0.0.8.pom, status: 401 Unauthorized ->

**Comment by hw-zhu** [comment]
I tried it again, it works to build the project org.talend.mdm.core.storage.sql v8.8.8-SNAPSHOT, I think you haven't enough right to access nexus, you can apply for the higher permission, then try it again.

**Comment by ims2098** [comment]
I don't know how to get these permissions. All I want to do is to change several lines in com.amalto.core.storage.datasource.RDBMSDataSource class. It doesn't work with MS SQL Server and Oracle.

**Comment by htyin** [comment]
Have you added the repository in your settings.xml and configured the username/password?
<repository>
	<id>thirdparty-releases</id>
	<name>thirdparty-releases</name>
	<url>https://artifacts-zl.talend.com/nexus/content/repositories/thirdparty-releases</url>
</repository>

>All I want to do is to change several lines in com.amalto.core.storage.datasource.RDBMSDataSource class. It doesn't work with MS SQL Server and Oracle.
Or you could create TMDM jira for the problem.

**Comment by htyin** [comment]
Please consider upgrading to Enterprise edition to get full support on your request.

**Comment by ims2098** [comment]
The main idea is to use Community edition. I see that it's strange to use Community edition with MS SQL Server
